require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/alugueis", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Aluguel. As you add validations to Aluguel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Aluguel.create! valid_attributes
      get alugueis_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      aluguel = Aluguel.create! valid_attributes
      get aluguel_url(aluguel)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_aluguel_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      aluguel = Aluguel.create! valid_attributes
      get edit_aluguel_url(aluguel)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Aluguel" do
        expect {
          post alugueis_url, params: { aluguel: valid_attributes }
        }.to change(Aluguel, :count).by(1)
      end

      it "redirects to the created aluguel" do
        post alugueis_url, params: { aluguel: valid_attributes }
        expect(response).to redirect_to(aluguel_url(Aluguel.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Aluguel" do
        expect {
          post alugueis_url, params: { aluguel: invalid_attributes }
        }.to change(Aluguel, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post alugueis_url, params: { aluguel: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested aluguel" do
        aluguel = Aluguel.create! valid_attributes
        patch aluguel_url(aluguel), params: { aluguel: new_attributes }
        aluguel.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the aluguel" do
        aluguel = Aluguel.create! valid_attributes
        patch aluguel_url(aluguel), params: { aluguel: new_attributes }
        aluguel.reload
        expect(response).to redirect_to(aluguel_url(aluguel))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        aluguel = Aluguel.create! valid_attributes
        patch aluguel_url(aluguel), params: { aluguel: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested aluguel" do
      aluguel = Aluguel.create! valid_attributes
      expect {
        delete aluguel_url(aluguel)
      }.to change(Aluguel, :count).by(-1)
    end

    it "redirects to the alugueis list" do
      aluguel = Aluguel.create! valid_attributes
      delete aluguel_url(aluguel)
      expect(response).to redirect_to(alugueis_url)
    end
  end
end
